[package]
name = "c509-cert"
version = "0.1.0"
edition = "2024"
description = "Parser for CBOR Encoded X.509 Certificates (C509), draft-ietf-cose-cbor-encoded-cert-19"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bkioshn/c509-cert"
readme = "README.md"
keywords = ["x509", "c509", "cbor", "certificate", "cose"]
categories = ["cryptography", "encoding"]

[dependencies]
hex = "0.4"
ipnet = "2.12.1"
macaddr = "1"
minicbor = { version = "2.3.0", features = ["std"] }
num-bigint = "0.4"
oid = "0.3.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.28.0", features = ["derive"] }
time = { version = "0.3", features = ["parsing", "formatting"] }
x509-parser = "0.18.1"
